swagger: '2.0'

info:

  description:  影评API
  version: 1.0.0
  title: server API
  
host: localhost
basePath: /
tags: 
  - name: user
    description: 用户
  - name: review
    description: 影评
  - name: comment
    description: 对影评的评论
    
schemes: 
  - http
  - https
  
paths:
  /createuser:
    post:
      tags:
        - user
      summary: 注册用户
      description: 直接输入昵称和密码注册
      parameters:
        - name: data
          in: body
          description: post data
          schema:
            required:
              - user_id
              - name
              - password
            properties:
              user_id:
                type: string
                description: 用户账号　前端生成
              name:
                type: string
                description: 用户昵称
              password:
                type: string
                description: 密码
      responses: 
        200:
          description: 注册成功
        400:
          description: 参数不全,客户端语法有问题
        401:
          description: 用户名或密码错误
                
  /login: 
    post:
      tags: 
        - user
      summary: 登录
      description: 账号密码登录
      parameters:
        - name: data
          in: body
          description: post data
          schema:
            required:  #required标明是否为必须传输的
              - user_id
              - password
            properties:
              user_id:
                type: string
                description: 用户账号
              password:
                type: string
                description: 用户密码
      responses:
        200:
          description: 登录成功
          schema:
            properties:
              token:
                type: string
                description: 传一个token保留,token就是user_id
        400:
          description: 参数不全，客户端语法有问题
        401:
          description: 用户名或密码错误


  /review:
    post: 
      tags: 
        - review
      summary: 创作影评
      parameters:
        - $ref: "#/parameters/token"
        - name: data
          in: body
          schema:
            $ref: "#/definitions/review"
      responses:
        200:
          description: 登录成功
        400:
          description: 参数不全，客户端语法有问题
        401:
          description: token错了, 权限不够   
    delete:
      tags:
        - review
      summary: 删除影评
      parameters:
        - $ref: "#/parameters/token"
        - name: review_id
          in: body
          schema:
            required:
              - review_id
            properties:
              comment_id:
                type: string
      responses:
        200:
          description: 删除成功
        401:
          description: token验证失败，权限不够

  /comment:
    post:
      tags:
        - comment
      summary: 发表评论
      parameters: 
        - $ref: "#/parameters/token"
        - name: comment
          in: body
          schema:
            $ref: "#/definitions/comment"
      responses:
        200:
          description: 评论发布成功
        401:
          description: token错误，没有权限
    delete:
      tags:
        - comment
      summary: 删除评论
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_comment
          in: body
          schema:
            properties:
              user_id:
                type: string
              comment_id:
                type: string
      responses:
        200:
          description: 删除成功
        401:
          description: token错误，没有权限     
  
  /people:
    get:
      tags:
        - user
      summary: 用户主页
      parameters:
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:
            properties:
              followers:
                description: 关注
                type: string
              fans:
                description: 粉丝
                type: string
        404:
          description: 没有该资源
        401:
          description: token错误，没有权限
 
    post: 
      tags:
        - user
      summary: 修改用户昵称
      parameters: 
        - $ref: "#/parameters/token"
        - name: new_name
          in: body
          schema:
            properties:
              new_name:
                type: string
      responses:
        200:
          description: 修改成功
        401:
          description: token错误，没有权限
          
  /people/change_password:
    post: 
      tags:
        - user
      summary: 修改用户密码
      parameters: 
        - $ref: "#/parameters/token"
        - name: userinfo
          in: body
          schema:
            properties:
              user_id:
                type: string
              password:
                type: string
              new_password:
                type: string
      responses:
        200:
          description: 修改成功
        401:
          description: token或密码错误,没有权限
  
  /people/review:
    get:
      tags: 
        - user
      summary: 用户主页-我的影评
      parameters: 
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_review"
        404:
          description: 没有该资源        
        401:
          description: token错误，没有权限
          
  /people/album:
    get:
      tags: 
        - user
      summary: 用户主页-专辑
      parameters: 
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:   
            properties:
              album_id: 
                type: string
              title: 
                type: string
              summary:
                type: string
              sum:
                description: 包含影评数
                type: string        
        404:
          description: 没有该资源
        401:
          description: token错误，没有权限 
    post:
      tags:
        - user
      summary: 创建专辑
      parameters: 
        - $ref: "#/parameters/token"
        - name: album_create
          in: body
          schema:
            properties: 
              album_id: 
                type: string
              title: 
                type: string
              summary:
                type: string
              sum:
                description: 包含影评数
                type: string
      responses:
        200:
          description: 专辑发布成功
        401:
          description: token错误，没有权限
 
    delete: 
      tags: 
        - user
      summary: 删除专辑
      parameters: 
        - $ref: "#/parameters/token"
        - name: album_delete
          in: body
          schema:
            properties:
              user_id:
                type: string
              album_id:
                type: string
      responses:
        200:
          description: 删除成功
        401:
          description: token错误，没有权限  
      
              
  /people/{album_id}:
    get:
      tags: 
        - user
      summary: 用户主页-专辑详情
      parameters: 
        - $ref: "#/parameters/token"
        - name: album_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_review"
        404:
          description: 没有该资源
        401:
          description: token错误，该用户没有登陆
  
  /people/collection:
    get:
      tags: 
        - user
      summary: 用户主页-收藏
      parameters: 
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_review"
        404:
          description: 没有该资源
        401:
          description: token错误，该用户没有登陆
      
  /people/set_portrait:
    post:
      tags:
        - user
      summary: 设置用户头像
      parameters:
        - $ref: "#/parameters/token"
        - name: data
          in: body
          schema:
            properties:
              user_picture:
                type: string
                description: 头像图片的url
      responses:
        200:
          description: OK
        401:
          description: token错了,不是该用户  

  
  /find:
    get:
      tags: 
        - review
      summary: 发现
      responses: 
        200: 
          description: 请求成功
          schema:
            type: array
            items: 
              $ref: "#/definitions/user_review"
        404:
          description: 没有找到资源
  
  /my_follow_review:
    get:
      tags: 
        - review
      summary: 关注界面
      parameters: 
        - $ref: "#/parameters/token"
      responses: 
        200: 
          description: 请求成功
          schema:
            type: array
            items: 
              $ref: "#/definitions/user_review"
        404:
          description: 没有找到资源
        401:
          description: token错误，没有权限

  /review_like:
    post: 
      tags: 
        - review
      summary: 对影评点赞
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_review
          in: body
          schema:
            properties: 
              user_id: 
                type: string
              review_id: 
                type: string
      responses:
        200:
          description: 点赞成功
        401:
          description: token错误，没有权限
    delete:
      tags: 
        - review
      summary: 取消影评点赞
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_review
          in: body
          schema:
            properties: 
              user_id: 
                type: string
              review_id: 
                type: string
      responses:
        200:
          description: 取消成功
        401:
          description: token错误，没有权限
  
  /review_collection:
    post: 
      tags: 
        - review
      summary: 收藏影评
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_review
          in: body
          schema:
            properties: 
              user_id: 
                type: string
              review_id: 
                type: string
      responses:
        200:
          description: 收藏成功
        401:
          description: token错误，没有权限

    delete:
      tags:
        - review
      summary: 取消收藏
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_review
          in: body
          schema:
            properties:
              user_id:
                type: string
              review_id:
                type: string
      responses:
        200:
          description: 取消成功
        401:
          description: token错误，没有权限  
          
  /comment_like:
    post: 
      tags: 
        - comment
      summary: 对评论点赞
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_comment
          in: body
          schema:
            properties: 
              user_id: 
                type: string
              comment_id: 
                type: string
      responses:
        200:
          description: 点赞成功
        401:
          description: token错误，没有权限
 
    delete:  
      tags:
        - comment
      summary: 取消点赞
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_comment
          in: body
          schema:
            properties:
              user_id:
                type: string
              comment_id:
                type: string
      responses:
        200:
          description: 取消成功
        401:
          description: token错误，没有权限  
 
  /my_follow:    
    get:
      tags: 
        - user
      summary: 用户关注的人
      parameters: 
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user"
        404:
          description: 没有该资源
        401:
          description: token错误，没有权限  
    
  /fans:
    get:
      tags: 
        - user
      summary: 用户粉丝
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          description: 要查询的用户的id
          in: body
          schema:
            properties:
              user_id:
                type: string
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user"
        404:
          description: 没有该资源
        401:
          description: token错误，没有权限  
          
  /follow_one:
    post:
      tags:
        - user
      summary: 关注用户
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_user
          in: body
          schema:
            properties:
              user_id: 
                description: 要关注的用户id
                type: string
      responses:
        200:
          description: 关注成功
        401:
          description: token错误，没有权限     
    delete: 
      tags:
        - user
      summary: 取消关注
      parameters: 
        - $ref: "#/parameters/token"
        - name: aim_user
          in: body
          schema:
            properties:
              user_id:
                description: 要取消关注的用户id
                type: string
      responses:
        200:
          description: 删除成功
        401:
          description: token错误，没有权限        
  
  /review/{review_id}:
    get:
      tags:
        - review
      summary: 查看具体影评
      parameters:
          - name: review_id
            in: path
            required: true
            type: string
      responses:
        200:
          description: 获取页面成功
          schema:
            type: array
            items:
              $ref: "#/definitions/user_comment"
          

definitions:
  review:
    description: 单纯的影评
    properties:
      review_id:
        type: string
      title: 
        type: string
      context:
        type: string
      time: 
        type: string
      tag: 
        type: string
      picture:
        type: string
        description: 传照片的url
      like_sum:
        type: string
        description: 点赞数
  user:
    properties:
      user_id:
        type: string
      user_picture:
        type: string
      user_name:
        type: string
        
  user_review:
    description: 一个信息块，同时显示影评和用户信息
    required:
      - review_id
      - user_id
    properties:
      user_id: 
        type: string
      name:
        type: string
      user_picture:
        type: string
      review_id:
        type: string
      title: 
        type: string
      context:
        type: string
      time: 
        type: string
      tag: 
        type: string
      picture:
        type: string
        description: 传照片的url
      like_sum:
        type: string
        description: 点赞数    
  
  comment:
    description: 评论信息
    required:
      - comment_id
      - review_id
    properties:
      review_id:
        type: string
      comment_id:
        type: string
      content:
        type: string
      time:
        type: string
      like_sum:
        type: string


  user_comment:
      description: 用户信息和评论的表
      required:
        - comment_id
        - user_id
      properties:
        user_id:
          type: string
        user_name:
          type: string
        user_picture:
          type: string
        comment_id:
          type: string
        content:
          type: string
        time:
          type: string
        like_sum:
          type: string
        comment_like:
          description: 本用户是否点赞
          type: boolean
        review_like: 
          type: boolean
        review_collection: 
          type: boolean
          
parameters:
  token:
      name: token
      in: header
      required: true
      type: string  
  
          


              
      
                
                
                

                      
                      
                    
                      
                      
    
          
                
                
                
                
                